name: Build and Deploy Code to Heroku

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  # Build the project and run tests
  build-job:
    environment:
      name: testing
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '17'
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Run Tests
      run: npm test
  
  # Deploy to Heroku job
  deploy:
    runs-on: ubuntu-latest
    needs: [build-job]
    steps:
      - uses: actions/checkout@v3
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}